import Script from 'next/script';
import type { Thing, WithContext } from 'schema-dts';

interface JsonLdProps {
  data: WithContext<Thing>;
}

/**
 * JSON-LD structured data component
 */
export function JsonLd({ data }: Readonly<JsonLdProps>) {
  // Generate unique ID based on the type or a fallback
  const schemaType = (data as { '@type'?: string })['@type'] ?? 'schema';
  const id = `json-ld-${schemaType}`;

  return (
    <Script
      id={id}
      type="application/ld+json"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: Required for JSON-LD structured data - content is generated by our schema functions, not user input
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
      strategy="beforeInteractive"
    />
  );
}
