import type { Thing, WithContext } from 'schema-dts';

interface JsonLdProps {
  data: WithContext<Thing>;
}

/**
 * JSON-LD structured data component.
 *
 * Rendered as a plain <script type="application/ld+json"> (the pattern the
 * Next.js JSON-LD guide recommends): next/script with beforeInteractive is
 * meant for executable scripts in the root layout and may relocate/duplicate
 * inline blocks, so crawlers that don't run JS could miss the structured data.
 */
export function JsonLd({ data }: Readonly<JsonLdProps>) {
  return (
    <script
      type="application/ld+json"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: Required for JSON-LD structured data - content is generated by our schema functions, not user input
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
